## Homework #1

### Set up the environment

You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from <a href='https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/01-intro/06-environment.md'>06-environment.md</a>.

In [20]:
import numpy as np
import pandas as pd

### Question 1

What's the version of NumPy that you installed?

You can get the version information using the `__version__` field:

In [21]:
np.__version__

'2.4.6'

### Getting the data

For this homework, we'll use the Car price dataset. Download it from <a href='https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'>here</a>. 

You can do it with wget:
```bash
wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
```
Or just open it with your browser and click "Save as...".

Now read it with Pandas.

In [22]:
data = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [23]:
data.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

### Question 2

How many records are in the dataset?

Here you need to specify the number of rows.

In [24]:
data.shape[0]   # alternative is len(data.index)

10000

### Question 3

How many fuel types are presented in the dataset?

In [25]:
data['fuel_type'].value_counts().head()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

### Question 4

How many columns in the dataset have missing values?

In [26]:
data.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [27]:
(data.isnull().sum() != 0).sum()

np.int64(2)

### Question 5

What's the maximum fuel efficiency of cars from Asia?

In [9]:
data.groupby('origin')['fuel_efficiency_mpg'].agg(['min', 'mean', 'max'])

         min       mean   max
origin
Asia    21.3  30.741015  41.2
Europe  20.7  30.552675  39.4
USA     19.8  29.097739  38.2

In [10]:
data[data.origin == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

### Question 6



1. Find the median value of "horsepower" column in the dataset.
2. Next, calculate the most frequent value of the same "horsepower". 
3. Use the `fillna` method to fill the missing values in "horsepower" with the most frequent value from the previous step.
4. Now, calculate the median value of "horsepower" once again.

Has it changed?

In [11]:
data['horsepower'].value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [12]:
median_horsepower = data['horsepower'].median()
median_horsepower

np.float64(254.0)

In [13]:
mode_horsepower = data['horsepower'].mode()[0]
mode_horsepower

np.float64(252.0)

In [14]:
data['horsepower'].fillna(mode_horsepower).median()

np.float64(252.0)

Yes, it decreased

### Question 7

1. Select all the cars from Asia.
2. Select only columns "vehicle_weight" and "model_year".
3. Select the first 7 values.
4. Get the underlying NumPy array. Let's call it 'X'.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

In [15]:
Asia_df = data[data['origin'] == 'Asia']
Asia_df = Asia_df[['vehicle_weight', 'model_year']]
Asia_df = Asia_df[:7]
Asia_df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [16]:
X = Asia_df.to_numpy()
XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [17]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [18]:
w = (XTX_inv @ X.T) @ y

In [19]:
w.sum()

np.float64(0.36919696904927707)

In [ ]:
> **Note**: we just implemented normal equation


$$w = (X^T X)^{-1} X^T y$$


We'll talk about it more in the next week (Machine Learning for Regression)